# Generated by Django 4.2.7 on 2023-12-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flxfituser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
